### ISSUE TITLE
Notify the client when the socket is closed

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [ugo-studio/flutter_p2p_connection#3]
It would be usefull to notify the client that the connection to the socket has been lost so that he can try to reconnect or simply notify the user. 

I believe it could be done fairly easily by adding an anonymous function call to the onDone event of socket.listen.

**Comment by ugo-studio** [comment]
I've added a `onCloseSocket` parameter to the `startSocket` and `connectToSocket` function:

```
await _flutterP2pConnectionPlugin.connectToSocket(
      ... 
      // runs when the socket is closed: `_flutterP2pConnectionPlugin.closeSocket()`
      onCloseSocket: () {
        print("closed socket");
      },
    );
```

Although I haven't publish it to flutter pub, you can install it from the github repository. 

```
  dependencies:
    flutter_p2p_connection:
      git:
        url: https://github.com/ugo-studio/flutter_p2p_connection.git

```
